import { useState } from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

import styles from "../styles/Home.module.css";

export default function Home() {
  const [peso, setPeso] = useState<string>("");
  const [altura, setAltura] = useState<string>("");
  const [menssage, setMenssage] = useState<string>("");

  function calcularIMC() {
    if (!peso || !altura)
      return setMenssage("Preencha os campos para funcionar corretamente!");

    if (!peso) {
      return setMenssage(
        "Preencha o campo de <strong>peso</strong> para funcionar corretamente!"
      );
    } else if(!altura) {
      return setMenssage(
        "Preencha o campo de <strong>altura</strong> para funcionar corretamente!"
      );
    }

    const resultadoDoCalculo = Number(peso.replace(/,/g, '.')) / (Number(altura.replace(/,/g, '.'))*Number(altura.replace(/,/g, '.')));

    // verifica situação
    if (resultadoDoCalculo < 17) {
      setMenssage(`Seu IMC é: ${String(resultadoDoCalculo.toFixed(2))?.replace(/\./g, ',')}<br />Você está muito abaixo do peso...`);
    } else if (resultadoDoCalculo >= 17 && resultadoDoCalculo <= 18.49) {
      setMenssage(`Seu IMC é: ${String(resultadoDoCalculo.toFixed(2))?.replace(/\./g, ',')}<br />Você está abaixo do peso...`);
    } else if (resultadoDoCalculo >= 18.5 && resultadoDoCalculo <= 24.99) {
      setMenssage(`Seu IMC é: ${String(resultadoDoCalculo.toFixed(2))?.replace(/\./g, ',')}<br />Seu peso está normal...`);
    } else if (resultadoDoCalculo >= 25 && resultadoDoCalculo <= 29.99) {
      setMenssage(`Seu IMC é: ${String(resultadoDoCalculo.toFixed(2))?.replace(/\./g, ',')}<br />Você está acima do peso...`);
    } else if (resultadoDoCalculo >= 30 && resultadoDoCalculo <= 34.99) {
      setMenssage(`Seu IMC é: ${String(resultadoDoCalculo.toFixed(2))?.replace(/\./g, ',')}<br />Você tem obesidade nível I`);
    } else if (resultadoDoCalculo >= 35 && resultadoDoCalculo <= 39.99) {
      setMenssage(`Seu IMC é: ${String(resultadoDoCalculo.toFixed(2))?.replace(/\./g, ',')}<br />Você tem Obesidade nível II`);
    } else if (resultadoDoCalculo >= 40) {
      setMenssage(`Seu IMC é: ${String(resultadoDoCalculo.toFixed(2))?.replace(/\./g, ',')}<br />Você tem Obesidade nível III`);
    }
  }

  return (
    <div className={styles.conteudo}>
      <Head>
        <title>Calcule seu IMC</title>
        <meta name="description" content="Generated by create next app" />
        <Link rel="icon" href="/favicon.ico" />
        <Link
          rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css"
        />
      </Head>

      <Image
        width={800}
        height={600}
        src="/caminhada.gif"
        alt=""
        className={styles.caminhada}
      />
      <form onSubmit={calcularIMC}>
        <h2 className={styles.titulo}>Calcule seu IMC</h2>
        <input
          className={styles.peso}
          type="number"
          placeholder="Peso"
          autoFocus
          value={peso}
          onChange={(e) => setPeso(e.target.value)}
        />
        <input
          className={styles.altura}
          type="number"
          placeholder="Altura"
          value={altura}
          onChange={(e) => setAltura(e.target.value)}
        />
        <input
          className={styles.calcularBtn}
          type="button"
          value="CALCULAR"
          onClick={calcularIMC}
        />
      </form>
      {!!menssage && (
        <div
          className={styles.menssage}
          dangerouslySetInnerHTML={{
            __html: menssage,
          }}
        />
      )}

      <footer className={styles.rodape}>
        <u>
          Copyright &copy; sozinho 2019 - {new Date().getFullYear()} Todos
          direitos reservados.
        </u>
      </footer>
    </div>
  );
}
